dist: xenial
language: python
cache: pip


env:
  global:
    # NOTE: Public push only token (can't be used to read or edit project info)
    - FOSSA_API_KEY=cbc317812661645ea400ab9ee6c7616a

matrix:
  include:
    - python: "2.7"
      env: TOXENV=py27
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.7"
      env: TOXENV=py37
    - python: "3.8"
      env: TOXENV=py38
    - python: "3.8"
      env: TOXENV=with-sslib-master
    - python: "3.8"
      env: TOXENV=lint

  allow_failures:
    - python: "3.8"
      env: TOXENV=with-sslib-master

install:
  - pip install tox coveralls

before_script:
  - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"

script:
  - tox
  - fossa

after_success:
  # Workaround to get coverage reports with relative paths.
  # FIXME: Consider refactoring the tests to not require the test aggregation
  # script being invoked from the `tests` directory, so that `.coverage` is
  # written to and .coveragrc can also reside in the project root directory, as
  # is the convention.
  - cp tests/.coverage .
  - coveralls --rcfile=tests/.coveragerc
