name: Scorecards analysis
on:
  branch_protection_rule:
  schedule:
    - cron: '21 6 * * 1'
  push:
    branches: [ develop ]
  workflow_dispatch:

permissions: {}

jobs:
  analysis:
    name: Scorecards analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write # for uploading to code-scanning dashboard
      id-token: write # for signing results
      actions: read
      contents: read

    steps:
      - name: "Checkout code"
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

      - name: "Run analysis"
        uses: ossf/scorecard-action@80e868c13c90f172d68d1f4501dee99e2479f7af
        with:
          results_file: results.sarif
          # sarif format required by upload-sarif action
          results_format: sarif
          # "repo_token" not set because personal access tokens are dangerous.
          # This means Branch-Protection check will not have correct results.
          publish_results: true

      - name: "Upload to code-scanning dashboard"
        uses: github/codeql-action/upload-sarif@29b1f65c5e92e24fe6b6647da1eaabe529cec70f
        with:
          sarif_file: results.sarif
