name: Scorecards analysis
on:
  branch_protection_rule:
  schedule:
    - cron: '21 6 * * 1'
  push:
    branches: [ develop ]
  workflow_dispatch:

permissions: {}

jobs:
  analysis:
    name: Scorecards analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write # for uploading to code-scanning dashboard
      id-token: write # for signing results
      actions: read
      contents: read

    steps:
      - name: "Checkout code"
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b

      - name: "Run analysis"
        uses: ossf/scorecard-action@e38b1902ae4f44df626f11ba0734b14fb91f8f86
        with:
          results_file: results.sarif
          # sarif format required by upload-sarif action
          results_format: sarif
          # "repo_token" not set because personal access tokens are dangerous.
          # This means Branch-Protection check will not have correct results.
          publish_results: true

      - name: "Upload to code-scanning dashboard"
        uses: github/codeql-action/upload-sarif@515828d97454b8354517688ddc5b48402b723750
        with:
          sarif_file: results.sarif
